source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'7.0'
#inhibit_all_warnings!
target 'DDSocialPodDemo’do
    pod 'DDSocial/Share' 
    pod 'DDSocial/MI'
    pod 'DDSocial/MiLiao'
    pod 'DDSocial/Wechat'
    pod 'DDSocial/Tencent'
    pod 'DDSocial/Sina'
    pod 'DDSocial/Facebook'
    pod 'DDSocial/Twitter'
    pod 'DDSocial/Google'
end

