source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'7.0'
#inhibit_all_warnings!
workspace 'DDSocialCodeDemo'
target 'DDSocialCodeDemo' do
   pod 'GoogleSignIn'
   pod 'FBSDKLoginKit'
   pod 'FBSDKShareKit'
   pod 'WeiboSDK', :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
   pod 'WechatOpenSDK', '~> 1.7.9'
   pod 'TTTAttributedLabel'
   pod 'LineSDK', '~> 4.0.3'
end
